### ISSUE TITLE
schema based definitions

### ISSUE THREAD

**Issue by arifshariati** [grafbase/grafbase#1706] opened 2024-05-08 06:31 UTC
**Describe the bug**
We do have Syntax error while running CLI `grafbase dev` asking for `expected field_definition`. 

**To Reproduce**
For the sake of example, following along the guide on grafbase website. Here is `grafbase.config.ts` file.

```typescript
import { graph, config } from "@grafbase/sdk";
const g = graph.Standalone();

g.type("Project", {

  title: g.string(),
  description: g.string(),
  image: g.url(),
  liveSiteUrl: g.url(),
  githubUrl: g.url(),
  category: g.string(),
});

export default config({ graph: g });
``` 

**Expected behavior**

**Examples**
If applicable, add examples of input and output to help explain your problem.

**Desktop (please complete the following information):**

- OS: macOS
- Version v0.23.0

**Additional context**
Definitely this does not work on grafbase platform as well due to deployment error.

**Comment by tomhoule** [comment] 2024-05-08 08:05
Hi! I can reproduce the issue, it looks like the most recent release may have broken something. I'm prioritizing fixing this issue now. Thanks for reporting.

**Comment by tomhoule** [comment] 2024-05-08 08:13
I'm making process on figuring out the source of the problem. We definitely need to improve the error there, but it looks like the source of the problem is that your graph doesn't define a `Query` type. As a workaround for now, something like this seems to work fine:

```ts
const g = graph.Standalone()

const project = g.type("Project", {
  title: g.string(),
  description: g.string(),
  image: g.url(),
  liveSiteUrl: g.url(),
  githubUrl: g.url(),
  category: g.string(),
});

g.query('allProjects', {
  returns: g.ref(project),
  resolver: 'allProjects',
})

export default config({
  graph: g,
})
```

**Comment by tomhoule** [comment] 2024-05-08 09:13
I confirmed the issue, it's when your config would produce a schema with an empty `Query` type. Fix is here, will be in the next CLI version: https://github.com/grafbase/grafbase/pull/1708

**Comment by tomhoule** [comment] 2024-05-08 09:13
In the meantime, if there is any field at all at the root, this won't happen.

**Closed** 2024-05-08 14:57 UTC
Labels: bug
